### PR TITLE
F #4556: Added option to conf VM logs location

### PR DESCRIPTION
**Pull request by feldsam**
This is usefull in HA Raft setup to easily share VM logs between HA nodes

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by feldsam** [comment]
hello, for some reason this doesnt work, would somebody point out why?

**Comment by al3xhh** [comment]
Hello @feldsam the commit message should be "F/B #<issue_number>: <commit_message>"

**Comment by feldsam** [comment]
Hi @al3xhh I know, but I was meaning that my code changes doesnt work :) and oned still logs to /var/log/one/vmid.log

**Comment by feldsam** [comment]
Hello, it is working in my env, now. What you think about this implementation? If this will be accepted or we agree on some other solution, then I plan to write blog post about setuping HA using RAFT and syncing logs using lsyncd.

I tested this with lsyncd and updated raft hook script, whichs stop/start lsyncd on nodes. Looks like that it is sufficient to just sync /var/lib/one/vms/ directory, when shared storage is used.

**Comment by feldsam** [comment]
Should I create issue for this?

**Comment by feldsam** [comment]
Example `lsyncd` config on `one1` frontend node:

```
targets = {
    'oneadmin@one1.feldcloud.net:/var/lib/one/vms/',
    'oneadmin@one2.feldcloud.net:/var/lib/one/vms/',
    'oneadmin@one3.feldcloud.net:/var/lib/one/vms/',
}

for _, target in ipairs( targets )
do
    if not string.match(target, "one1.feldcloud.net") then
        sync{
          default.rsync,
          source = "/var/lib/one/vms/",
          target = target,
          rsync = {
            archive = true,
            rsh = "/usr/bin/ssh -l oneadmin -i /var/lib/one/.ssh/id_rsa -o StrictHostKeyChecking=no"
          },
          delay = 1
        }
    end
end
```

In RAFT hook `lsyncd` service is started on the leader and stopped on followers.

**Comment by rsmontero** [comment]
Could you configure lsyncd to just sync [0-9]*.log files in /var/log/one/?

**Comment by feldsam** [comment]
Hi, `lsyncd` uses `rsync`, which doesn't speak regex. In VMS location are also other files, and this seemed the most natural solution to me :)

**Review by rsmontero — APPROVED** [review]

**Comment by rsmontero** [comment]
Merged as per b9e2dcc4ebf15cd489ecfc48a1ca61d3f6844e17

**Pull request closed without merging**
