### PR TITLE
B #3373: pass VM template via STDIN

### PR DESCRIPTION
**Pull request by atodorov-storpool**
for _tm/*/{pre,post,fail}migrate_

Signed-off-by: Anton Todorov <a.todorov@storpool.com>

### CODE REVIEW

**Comment by xorel** [comment]
Hello @atodorov-storpool 
I modified it so the action scripts (tm/*/{pre,post,fail}migrate) receives VM template on stdin. 
Do you think you can test it? 
https://github.com/OpenNebula/one/commit/690dfb09f4398c14f010bf2cc9cb1c54c1925c55
thanks

**Comment by atodorov-storpool** [comment]
Hi @xorel,

I think that the template should be stored in a temporary file that should be red by xpath_rb

Please take a look at https://github.com/OpenNebula/addon-storpool/blob/master/tm/storpool/premigrate#L47

And the patched xpath.rb :
https://github.com/OpenNebula/addon-storpool/blob/master/datastore/xpath-sp.rb
(the patch is not perfect, it just works for me :D )

**Comment by xorel** [comment]
I don't think it's necessary. The error (``Argument list too long``) is only hit when the parameter is passed as a positional argument but still could be stored in a variable and passed through a pipe via stdin like here: 
https://github.com/OpenNebula/one/commit/690dfb09f4398c14f010bf2cc9cb1c54c1925c55#diff-606e289f74e14c1c2e1c35de93119c31R127

**Comment by atodorov-storpool** [comment]
Fair enough :)

Can't spot other issues

**Comment by xorel** [comment]
Created https://github.com/OpenNebula/one/pull/3583 instead

**Pull request closed without merging**
