### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by FlorianHeigl**
The greek _Logos_ means both Reason and Wisdom, and while we know those logos have no other effect than being shown in the UI, it looks a lot nicer - with this patch they are no longer just mentioning old OS versions or missing common choices.

### CODE REVIEW

**Comment by feldsam** [comment]
Hello, did you have context scripts for that new OSes? Especially for suse and freebsd? thank you.

**Comment by FlorianHeigl** [comment]
Hi,

I collected + written something for both, neither is really upstream quality.
If you can wait for the weekend, I’ll put them online somewhere.

**Comment by vholer** [comment]
Hi, @feldsam! Regarding the openSUSE, current beta contextualization packages [ver. 5.3.80](https://github.com/OpenNebula/addon-context-linux/releases/tag/v5.3.80) are also built for the openSUSE 42.x with basic support added by @kvaps of the WEDOS. In case you want to test something very fresh... Thanks.

**Comment by feldsam** [comment]
Hi @vholer, thank you, I testing it now and just works :) perfect.

@FlorianHeigl - I grab your suse logo, but it is too big, logos shoud have 90x90px, @vholer am I right?

**Comment by vholer** [comment]
> logos should have 90x90px, @vholer am I right?

Don't know, this is a question on @juanmont ?

**Comment by rsmontero** [comment]
Logos scaled in #1813.

**Comment by abelCoronado93** [comment]
For the new logos it is preferable that they are 90x90.

Thanks!

**Pull request merged**
