### PR TITLE
B #3590: change package vnc for git

### PR DESCRIPTION
**Pull request by jloboescalona2**
this PR apply
-master
-one-5.8

### CODE REVIEW

**Comment by vholer** [comment]
My guess is that (at least) precise commit must be specified to be able to provide (as much as possible) consistent and reproducible builds.

**Comment by feldsam** [comment]
Hi there, I build own version of OpenNebula including this commit, build was success, but novnc in sunstone wasn't work and in log are errors:

```
Client must support 'binary' or 'base64' protocol
``` 

after reverting this commit, novnc is working again

**Comment by jloboescalona2** [comment]
@feldsam, hi, the VM has password?

**Comment by feldsam** [comment]
Hi, no.

**Comment by jloboescalona2** [comment]
u can send me a image please

**Comment by feldsam** [comment]
Hi, I rebuild and install without this commit. I see nothing, just white screen and in console are error 400 and in novnc log is what I already sent

**Comment by jloboescalona2** [comment]
@feldsam, you can try this commit  https://github.com/OpenNebula/one/pull/3670/commits/d1105074fa0b35e0c53b55d6527751350741d927

**Comment by feldsam** [comment]
@jloboescalona2 working now!

**Pull request merged**
