### PR TITLE
F #3366: allow alternative search base for ldap groups

### LINKED ISSUE #3366: LDAP group base cannot be different from user base
**Description**
When selecting a group mapping, the groups are searched below the *same* base as the users. In many real world ldap trees, the groups are though found below a different tree.

**To Reproduce**
Create an ldap tree as follows:

ou=groups,ou=..,c=ch
ou=users,ou=..,c=ch

Use ou=users,ou=..,c=ch as basedn -> allows login, but not the group mapping to work
Use ou=groups,ou=..,c=ch as basedn -> does not allow login

**Expected behavior**
It should be possible to define 2 different bases, one for groups, one for users

**Details**
I think only the ruby implementation needs to be updated

**Additional context**

Question: if we code this behaviour, can you merge it into a version soon (like 5.8.4)?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

### PR DESCRIPTION
**Pull request by asteven**
Fixes #3366.

I also wanted to update the docs but could not find them in the repo.
If you point me at the repo/place where they live I can also update those.

### CODE REVIEW

**Comment by telmich** [comment]
:+1:

**Comment by telmich** [comment]
We have tested this one in production and would be happy to see it merged in one of the next releases

**Comment by tinova** [comment]
Hi asteven, thanks for your contribution!

You can find the documentation repo here: https://github.com/OpenNebula/docs. A PR to master is most welcome.

**Comment by tinova** [comment]
taking it to one-5.8

**Comment by tinova** [comment]
Thanks a lot for the contribution

**Pull request merged**
