### PR TITLE
B #5079: Fix IPv6 Addresses in vRouters with IP spoofing

### PR DESCRIPTION
**Pull request by kvanals**
While using the virtual router framework, it was discovered that traffic to IPv6 virtual / floating IPs was being blocked by ip6tables.  Upon further investigation, IPv6 vRouter IPs were not being properly added to the ipset.  This pull request is to resolve this issue and has been tested in an OpenNebula lab environment.

### CODE REVIEW

**Comment by xorel** [comment]
Only `:vrouter_ip6` will actually get to the CONTEXT, could you update it?

**Comment by kvanals** [comment]
Looking into VirtualMachineContext.cc, that seems true, but it seems like ip6_global and ip6_link should be removed as well, leaving just ip6, ip6_ula, and vrouter_ip6.  Otherwise I matched what was already defined for the IPv6 addresses in that list.  It's been a long day and I could be mistaken, however.

**Comment by rsmontero** [comment]
Not sure what happened, sorry for not looking into this earlier, but there are way too many changes. Not sure what the actual files are target by this PR. Could you please update it with the actual changes? THANKS!

**Comment by kvanals** [comment]
> Not sure what happened, sorry for not looking into this earlier, but there are way too many changes. Not sure what the actual files are target by this PR. Could you please update it with the actual changes? THANKS!

I'm not sure what happened either.  It was a single file change.  I'll see about getting this corrected somehow.  The only commit needed is https://github.com/kvanals/one/commit/4043a50ef6909651b201f2771a370032f76ab652

**Comment by kvanals** [comment]
I'm going to close this PR and open a new one.

**Pull request closed without merging**
