### PR TITLE
F #2161 Skip loopback IP on vxlan tep

### PR DESCRIPTION
**Pull request by xorel**

### CODE REVIEW

**Comment by hydro-b** [comment]
Hi Jan,

This gives me the following ruby error:

Thu Nov 15 14:15:14 2018 [Z0][VMM][D]: Message received: LOG I 50 /var/tmp/one/vnm/vxlan/vxlan.rb:100:in `block in get_interface_first_ip': undefined method `starts_with?' for #<MatchData "    inet 127.0.0.1" 1:"127.0.0.1"> (NoMethodError)

**Comment by xorel** [comment]
Oops, thanks for the catch. I fixed this typo locally but pushed the wrong one, anyway should be fine now.

**Comment by hydro-b** [comment]
Hmm, still fails for me:

Thu Nov 15 15:55:27 2018 [Z0][VMM][D]: Message received: LOG I 50 /var/tmp/one/vnm/vxlan/vxlan.rb:100:in `block in get_interface_first_ip': undefined method `start_with?' for #<MatchData "    inet 127.0.0.1" 1:"127.0.0.1"> (NoMethodError)

**Comment by xorel** [comment]
Really not my day today, should be fine now.

**Pull request merged**
