### PR TITLE
B #5483: Add 'flow' folder to LIB_OCA_CLIENT_DIRS

### PR DESCRIPTION
**Pull request by danhigham**
There is a an issue in install.sh when run on Mac OS, instead of creating the folder 'src/oca/ruby/opennebula/flow', the files that follow in the RUBY_OPENNEBULA_LIB_FLOW_FILES list get written in turn to a FILE with the path 'src/oca/ruby/opennebula/flow'. This is due to a subtle difference in the way the 'cp' command works in linux and Mac OS.

### CODE REVIEW

**Review by al3xhh — CHANGES_REQUESTED** [review]
Why do we need this change?

We have that directory added here:

```
  LIB_DIRS="$LIB_LOCATION/ruby \                                                  
            $LIB_LOCATION/ruby/opennebula \                                       
            $LIB_LOCATION/ruby/opennebula/flow \ ```

**Comment by danhigham** [comment]
> Why do we need this change?
> 
> We have that directory added here:
> 
> ```
>   LIB_DIRS="$LIB_LOCATION/ruby \                                                  
>             $LIB_LOCATION/ruby/opennebula \                                       
>             $LIB_LOCATION/ruby/opennebula/flow \ ```
> ```

The use case here is if you are only installing the CLI using the install script by using the -c flag

**Comment by al3xhh** [comment]
Thanks for the comment!

But instead of adding the directory where you added it, I prefer this:

```
diff --git a/install.sh b/install.sh
index a3d0da4411..d4b2a7f602 100755
--- a/install.sh
+++ b/install.sh
@@ -540,7 +540,8 @@ ONEFLOW_DIRS="$ONEFLOW_LOCATION/lib \
               $ONEFLOW_LOCATION/lib/models"
 
 LIB_OCA_CLIENT_DIRS="$LIB_LOCATION/ruby \
-                 $LIB_LOCATION/ruby/opennebula"
+                     $LIB_LOCATION/ruby/opennebula \
+                     $LIB_LOCATION/ruby/opennebula/flow"
 
 LIB_CLI_CLIENT_DIRS="$LIB_LOCATION/ruby/cli \
                      $LIB_LOCATION/ruby/cli/one_helper"
```

Could you please update the PR so we can merge it?

Thanks!!!!

**Comment by danhigham** [comment]
> LIB_OCA_CLIENT_DIRS

Ah! That _does_ seem much cleaner! I changed the PR, as requested.

**Review by al3xhh — APPROVED** [review]

**Comment by rsmontero** [comment]
Merge as per 07be714219af3e448e10b09d336831176da4804b

**Pull request closed without merging**
